//Elementos da pagina de Cadastro
export const ELEMENTS = {
    url: 'https://www.automationexercise.com/signup',
    checkboxMr: '#id_gender1',
    checkboxMrs: '#id_gender2',
    name: '#name',
    email: '[data-qa="email"]',
    password: '[data-qa="password"]',
    dia: '[data-qa="days"]',
    mes: '[data-qa="months"]',
    ano: '[data-qa="years"]',
    receberNewsletter: '#newsletter',
    receberOfertas: '#optin',
    firstName: '[data-qa="first_name"]',
    lastName: '[data-qa="last_name"]',
    company: '[data-qa="company"]',
    address: '[data-qa="address"]',
    address2: '[data-qa="address2"]',
    country: '[data-qa="country"]',
    state: '[data-qa="state"]',
    city: '[data-qa="city"]',
    zipCode: '[data-qa="zipcode"]',
    mobileNumber: '[data-qa="mobile_number"]',
    botaoCadastrar: '[data-qa="create-account"]',
    mensagemSucesso: '.signup-form > h2',
    botaoCreateAccount: '[data-qa="create-account"]',
    botaoContinue: '[data-qa="continue-button"]',
    botaoDeleteAccount: 'a[href="/delete_account"]',
    logout:'a[href="/logout"]',   
}